### ISSUE TITLE
ImportError: cannot import name 'insert_into'

### ISSUE THREAD

**Issue by Vigor111** [limdauto/drf_openapi#78]
* DRF OpenAPI version: 1.0.0
* Python version: 3.6
* Operating System: macOs Sierra 10.12

![screen shot 2017-11-01 at 10 30 52 pm](https://user-images.githubusercontent.com/30640392/32274806-5d183e54-bf54-11e7-8222-92d1774967f3.png)

**Comment by werwty** [comment]
@Vigor111 This is a djangorestframework 3.7 compatibility issue, see: https://github.com/limdauto/drf_openapi/issues/64

**Comment by Vigor111** [comment]
I am using djangorestframework 3.7.1.
Is it impossible to use it?

**Comment by alantrick** [comment]
The djangorestframework 3.7 patches have been merged, so you can use drf_openapi now. I don't know if pip is updated yet though, so you might need to use it straight from this repo.

**Comment by yihengli** [comment]
Confirmed that the master branch is working with 3.7. However, the pip version is still the outdated one

**Comment by salexkidd** [comment]
Nice fix! I'm waiting for release on pip 😄

**Comment by erikkvale** [comment]
Yes, please update on pip. Much appreciated.

**Comment by windhamwong** [comment]
You can always `pip install git+https://github.com/limdauto/drf_openapi.git`

**Comment by werwty** [comment]
Compatibility patch has now been released on PyPI: https://pypi.python.org/pypi/drf-openapi/1.0.1
`pip install drf_openapi` will get you the latest
